### ISSUE TITLE
The matrix D_u/U_n/D_I/U_I/T definition

### ISSUE THREAD

**Issue by wangxk9999** [wdvorkin/differentially_private_OPF#1]
Hello, dear wdvorkin
  I am studying your DP_CC_OPF paper, it is a great job. 
  I have some questions about D_u/U_n/D_I/U_I/T definition in the program. Are they related to the flow direction of nodes? 
  I am checking the Fig. 4. in `A. Papavasiliou, “Analysis of distribution locational marginal prices,”
IEEE Trans. Smart Grid, vol. 9, no. 5, pp. 4872–4882, 2017.`，and can’t understand how these matrices represent this figure. 
Can you explain or send me some explanatory materials？ wangxk9999@gmail.com
Thank you very much.

**Comment by wdvorkin** [comment]
For a distribution feeder with _N_ nodes and _L_ lines, an _N x N_ matrix _D_n_ is built such that its _n_-th column assigns ones to all downstream ("below") nodes relative to node _n_, including node _n_ itself. An _N x N_ matrix _U_n_ is similar, but its _n_-th column assigns ones to upstream ("above") nodes relative to node _n_, not including node _n_. You can verify that those matrices are asymmetric and _U_n_ + _D_n_ = matrix of ones, meaning that all upstream and downstream nodes relative to any node _n_ are accounted for. 

An _N x L_ matrix _D_l_  is built such that its _n_-th raw assigns ones to all lines that are in the downstream ("below") relative to node _n_. An _N x L_ matrix _U_l_  is built similarly but focuses on the upstream  ("above")  lines. One also verifies that these two matrices are asymmetric, and their sum yields a matrix of ones meaning that all lines are accounted for. Hence the integrity of the grid is preserved.  

For visualization, it would help to numerate not only the nodes but also the lines on the figure you mentioned.  For line numbering, you can refer to data file DP_CC_OPF/testcase/feeder15/lines.csv. 

Hope this helps!

**Comment by wangxk9999** [comment]
Thank you very much for your reply, wdvorkin
The _D_n/U_n_ matrix is  consistent with what you said, although they are N×L matrices, I think this has no effect.
N x L matrix _D_l_ ，nodes number are rows,  columns are line numbers.  if nodes are downstream of line, it assigns one in the matrix. From this point of view, it is consistent with your matrix D_l/U_l. 
I don’t know if this explanation is the same as what you mean.

Thanks again for your help！
